DELETE FROM public.items;
DELETE FROM public.categories;

INSERT INTO public.categories (id, name, icon, collapsible, sort_order, is_active)
VALUES
  ('nim-baguette-section', 'نان سفید', '🥖', true, 1, true),
  ('rogan-section', 'روگن', '🥖', true, 2, true),
  ('gata-section', 'گاتا', '🍪', true, 3, true),
  ('eshtrodel-section', 'اشترودل', '🥐', true, 4, true),
  ('pirashki-section', 'ساندویچ کوچک', '🌭', true, 5, true),
  ('shirmal-section', 'شیرمال', '🍞', true, 6, true),
  ('simyt-section', 'سیمیت', '🥯', true, 7, true),
  ('croissant-section', 'کروسان', '🥐', true, 8, true),
  ('pie-section', 'پای', '🥧', true, 9, true),
  ('misc-3-section', 'شیرینی خشک', '🍪', true, 10, true),
  ('donut-section', 'پیراشکی (دونات)', '🍩', true, 11, true),
  ('khamir-torsh-section', 'خمیر ترش', '🌾', true, 12, true),
  ('toast-section', 'تست', '🍞', true, 13, true),
  ('salad-section', 'نان خشک', '🥗', true, 14, true),
  ('cake-section', 'کیک ها', '🎂', true, 15, true),
  ('cookie-section', 'کوکی و کاندیل', '🍪', true, 16, true),
  ('sokharis-section', 'سوخاری', '🍞', true, 17, true),
  ('shirini-tar-section', 'شیرینی تر', '🧁', true, 18, true),
  ('mochi-section', 'موچی', '🍡', true, 19, true);

INSERT INTO public.items (id, category_id, name, tray_mode, sort_order, is_active)
VALUES
  ('nim-baguette', 'nim-baguette-section', 'نیم باگت', false, 1, true),
  ('sandwichi', 'nim-baguette-section', 'ساندویچی', false, 2, true),
  ('ghalami', 'nim-baguette-section', 'قلمی', false, 3, true),
  ('barbari-sadeh', 'nim-baguette-section', 'بربری ساده', false, 4, true),
  ('barbari-korei', 'nim-baguette-section', 'بربری کره ای', false, 5, true),
  ('hamburger', 'nim-baguette-section', 'همبرگر', false, 6, true),
  ('mini-hamburger', 'nim-baguette-section', 'مینی همبرگر', false, 7, true),
  ('finger-food', 'nim-baguette-section', 'فینگر فود', false, 8, true),
  ('sandwichi-mac', 'nim-baguette-section', 'ساندویچی مک', false, 9, true),
  ('burger-mac', 'nim-baguette-section', 'برگر مک', false, 10, true),
  ('khamir-pizza', 'nim-baguette-section', 'خمیر پیتزا', false, 11, true),
  ('nim-baguette-rogan', 'rogan-section', 'نیم باگت روگن', false, 1, true),
  ('sandwichi-rogan', 'rogan-section', 'ساندویچی روگن', false, 2, true),
  ('ghalami-rogan', 'rogan-section', 'قلمی روگن', false, 3, true),
  ('mini-burger-rogan', 'rogan-section', 'مینی برگر روگن', false, 4, true),
  ('hamburger-rogan', 'rogan-section', 'همبرگر روگن', false, 5, true),
  ('barbari-rogan', 'rogan-section', 'بربری روگن', false, 6, true),
  ('charki-chavdar', 'rogan-section', 'چارکی چاودار', false, 7, true),
  ('super-siah', 'rogan-section', 'سوپر سیاه', false, 8, true),
  ('haft-giah', 'rogan-section', 'هفت گیاه', false, 9, true),
  ('bagel', 'rogan-section', 'بیگل', false, 10, true),
  ('gata-sadeh', 'gata-section', 'گاتا ساده', false, 1, true),
  ('gata-khorma', 'gata-section', 'گاتا خرما', false, 2, true),
  ('gata-gerdoo', 'gata-section', 'گاتا گردو', false, 3, true),
  ('gata-miveyi', 'gata-section', 'گاتا میوه ای', false, 4, true),
  ('gata-karebadaam', 'gata-section', 'گاتا کره بادام', false, 5, true),
  ('eshtrodel-pizza', 'eshtrodel-section', 'اشترودل پیتزایی', false, 1, true),
  ('eshtrodel-gerdoo', 'eshtrodel-section', 'اشترودل گردو', false, 2, true),
  ('eshtrodel-albaloo', 'eshtrodel-section', 'اشترودل آلبالو', false, 3, true),
  ('beef-cheese', 'pirashki-section', 'بیف چیز', false, 1, true),
  ('mazeh', 'pirashki-section', 'مزه', false, 2, true),
  ('shirmal-gisoo', 'shirmal-section', 'شیرمال گیسو', false, 1, true),
  ('shirmal-makhsoos', 'shirmal-section', 'شیرمال مخصوص', false, 2, true),
  ('simyt', 'simyt-section', 'سیمیت', false, 1, true),
  ('simyt-sobhaneh', 'simyt-section', 'سیمیت صبحانه (پنیر)', false, 2, true),
  ('simyt-khorma', 'simyt-section', 'سیمیت خرما', false, 3, true),
  ('croissant-sadeh', 'croissant-section', 'کروسان ساده', false, 1, true),
  ('croissant-nutella', 'croissant-section', 'کروسان نوتلا', false, 2, true),
  ('croissant-badam', 'croissant-section', 'کروسان بادام', false, 3, true),
  ('pie-sib', 'pie-section', 'پای سیب', true, 1, true),
  ('pie-ananas', 'pie-section', 'پای آناناس', true, 2, true),
  ('cake-yazdi', 'misc-3-section', 'کیک یزدی', true, 1, true),
  ('shirini-keshmeshi', 'misc-3-section', 'شیرینی کشمشی', true, 2, true),
  ('saaq-aroos', 'misc-3-section', 'ساق عروس', true, 3, true),
  ('danmarki', 'misc-3-section', 'دانمارکی', true, 4, true),
  ('lando', 'misc-3-section', 'لندو', true, 5, true),
  ('danish', 'misc-3-section', 'دنیش', true, 6, true),
  ('shoorini', 'misc-3-section', 'شورینی', true, 7, true),
  ('mami-nutella', 'misc-3-section', 'مامی نوتلا', true, 8, true),
  ('muffin-sadeh', 'misc-3-section', 'مافین ساده', false, 9, true),
  ('muffin-chocolate', 'misc-3-section', 'مافین شکلات', false, 10, true),
  ('muffin-nescafe', 'misc-3-section', 'مافین نسکافه', false, 11, true),
  ('lava', 'misc-3-section', 'لاوا', false, 12, true),
  ('zaban', 'misc-3-section', 'زبان', false, 13, true),
  ('ajma', 'misc-3-section', 'آجما/آچما', false, 14, true),
  ('zaban-keshmeshi', 'misc-3-section', 'زبان کشمشی', false, 15, true),
  ('swissi-mrabai', 'misc-3-section', 'سوئیسی مربایی', true, 16, true),
  ('swissi-nutella', 'misc-3-section', 'سوئیسی نوتلایی', true, 17, true),
  ('mikado', 'misc-3-section', 'میکادو', true, 18, true),
  ('donut-shekari', 'donut-section', 'دونات شکری', false, 1, true),
  ('donut-kreamddar', 'donut-section', 'دونات کرمدار', false, 2, true),
  ('donut-kakaoyi', 'donut-section', 'دونات کاکائویی', false, 3, true),
  ('pirashki-hotdog', 'donut-section', 'پیراشکی هات داگ', false, 4, true),
  ('paneh', 'khamir-torsh-section', 'پانه', false, 1, true),
  ('chiapata', 'khamir-torsh-section', 'چیاپاتا', false, 2, true),
  ('baguette-original', 'khamir-torsh-section', 'باگت اورجینال', false, 3, true),
  ('ekmak', 'khamir-torsh-section', 'اکمک', false, 4, true),
  ('artisan', 'khamir-torsh-section', 'آرتیزن', false, 5, true),
  ('asal-gerdoo', 'khamir-torsh-section', 'عسل گردو', false, 6, true),
  ('nan-sir', 'khamir-torsh-section', 'نان سیر', false, 7, true),
  ('focaccia', 'khamir-torsh-section', 'فوکاچیا', false, 8, true),
  ('toast-bozorg', 'toast-section', 'تست بزرگ', false, 1, true),
  ('toast-kuchak', 'toast-section', 'تست کوچک', false, 2, true),
  ('toast-rogan-bozorg', 'toast-section', 'تست روگن بزرگ', false, 3, true),
  ('toast-rogan-kuchak', 'toast-section', 'تست روگن کوچک', false, 4, true),
  ('toast-swital-bozorg', 'toast-section', 'تست سویتال بزرگ', false, 5, true),
  ('toast-swital-kuchak', 'toast-section', 'تست سویتال کوچک', false, 6, true),
  ('toast-caesar', 'toast-section', 'تست سزار', false, 7, true),
  ('salad-sirdar', 'salad-section', 'سالاد سیردار', false, 1, true),
  ('soup-konjedi', 'salad-section', 'سوپ کنجدی', false, 2, true),
  ('nan-protein', 'salad-section', 'نان پروتئین', false, 3, true),
  ('khoshk-shevid', 'salad-section', 'خشک شوید', false, 4, true),
  ('khoshk-tokhme', 'salad-section', 'خشک تخمه', false, 5, true),
  ('khoshk-kajand', 'salad-section', 'خشک کنجد', false, 6, true),
  ('nan-chai', 'salad-section', 'نان چای', false, 7, true),
  ('nan-ghandi', 'salad-section', 'نان قندی', false, 8, true),
  ('nan-jo', 'salad-section', 'نان جو', false, 9, true),
  ('cake-sib-darchin', 'cake-section', 'کیک سیب و دارچین', false, 1, true),
  ('cake-sobhaneh', 'cake-section', 'کیک صبحانه', true, 2, true),
  ('cake-carrot', 'cake-section', 'کیک هویج', false, 3, true),
  ('brownie', 'cake-section', 'براونی', true, 4, true),
  ('pudding-asali', 'cake-section', 'پودینگ عسلی', true, 5, true),
  ('cake-nutella-kuchak', 'cake-section', 'کیک نوتلا کوچک', false, 6, true),
  ('cookie-shokolati', 'cookie-section', 'کوکی شکلاتی', false, 1, true),
  ('cookie-cappuccino', 'cookie-section', 'کوکی کاپوچینو', false, 2, true),
  ('cookie-redvelvet', 'cookie-section', 'کوکی ردولوت', false, 3, true),
  ('cookie-sadeh-sefid', 'cookie-section', 'کوکی ساده (سفید)', false, 4, true),
  ('cookie-rejimi', 'cookie-section', 'کوکی رژیمی', false, 5, true),
  ('candil', 'cookie-section', 'کاندیل', false, 6, true),
  ('sokharis-shirin', 'sokharis-section', 'سوخاری شیرین', false, 1, true),
  ('sokharis-rogan', 'sokharis-section', 'سوخاری روگن', false, 2, true),
  ('napoleoni', 'shirini-tar-section', 'ناپلئونی', true, 1, true),
  ('nan-khamei-bozorg', 'shirini-tar-section', 'نان خامه ای بزرگ', true, 2, true),
  ('nan-khamei-kuchak', 'shirini-tar-section', 'نان خامه ای کوچک', true, 3, true),
  ('nan-khamei-moozi', 'shirini-tar-section', 'نان خامه ای موزی', true, 4, true),
  ('eclair-bozorg', 'shirini-tar-section', 'اکلر بزرگ', true, 5, true),
  ('eclair-kuchak', 'shirini-tar-section', 'اکلر کوچک', true, 6, true),
  ('faransavi', 'shirini-tar-section', 'فرانسوی', true, 7, true),
  ('dessert-cheesecake', 'shirini-tar-section', 'مینی چیز کیک', false, 8, true),
  ('dessert-tiramisu', 'shirini-tar-section', 'دسر تیرامیسو', false, 9, true),
  ('dessert-mivei-shatoot', 'shirini-tar-section', 'دسر میوه ای شاتوت', false, 10, true),
  ('dessert-mivei-tootfarangi', 'shirini-tar-section', 'دسر میوه ای توت فرنگی', false, 11, true),
  ('dessert-mivei-zardaloo', 'shirini-tar-section', 'دسر میوه ای زردآلو', false, 12, true),
  ('dessert-mivei-porteghal', 'shirini-tar-section', 'دسر میوه ای پرتغال', false, 13, true),
  ('roolet-sadeh', 'shirini-tar-section', 'رولت ساده', true, 14, true),
  ('roolet-shatoot', 'shirini-tar-section', 'رولت شاتوت', true, 15, true),
  ('roolet-kakao', 'shirini-tar-section', 'رولت کاکائو (نوتلا)', true, 16, true),
  ('roolet-pesteh', 'shirini-tar-section', 'رولت پسته ای', true, 17, true),
  ('roolet-lotus', 'shirini-tar-section', 'رولت لوتوس', true, 18, true),
  ('roolet-caramel', 'shirini-tar-section', 'رولت کاراملی', true, 19, true),
  ('roolet-nargil', 'shirini-tar-section', 'رولت نارگیلی', true, 20, true),
  ('roolet-zardaalu', 'shirini-tar-section', 'رولت زردآلو', true, 21, true),
  ('roolet-ghahve', 'shirini-tar-section', 'رولت پودر قهوه', true, 22, true),
  ('roolet-picasso', 'shirini-tar-section', 'رولت پیکاسو', true, 23, true),
  ('cupcake', 'shirini-tar-section', 'کاپ کیک', false, 24, true),
  ('cheesecake-chocolate', 'shirini-tar-section', 'چیز کیک برشی شکلات', false, 25, true),
  ('cheesecake-white', 'shirini-tar-section', 'چیز کیک برشی سفید', false, 26, true),
  ('mochi-tootfarangi', 'mochi-section', 'موچی توت فرنگی', false, 1, true),
  ('mochi-nutella', 'mochi-section', 'موچی نوتلا', false, 2, true),
  ('mochi-caramel', 'mochi-section', 'موچی کارامل', false, 3, true),
  ('mochi-shatoot', 'mochi-section', 'موچی شاتوت', false, 4, true),
  ('mochi-ranginkaman', 'mochi-section', 'موچی رنگین کمان', false, 5, true);
